name: Track 4 Print Metadata
run-name: This ${{ github.actor }} is starting out GitHub Actions

on: [push]

jobs:
  print-job:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print messages in PowerShell
        run: |
          Write-Output "Hello from PowerShell!"
          Write-Output "OS Runner Type: ${{ runner.os }}"
          Write-Output "Event Name: ${{ github.event_name }}"
          Write-Output "Branch Name: ${{ github.ref_name}}"
          Write-Output "Repository Name: ${{ github.repository }}"

          Write-Output "Files in Github Workspace:"
          tree "$env:GITHUB_WORKSPACE" /F