name: Track 4 Print Metadata
run-name: This ${{ github.actor }} is starting out GitHub Actions
on: [push]
jobs:
  print-job:
    runs-on: windows-latest
    steps:
      - name: Print messages in PowerShell
        run: |
          Write-Output "Hello from PowerShell!"
          Write-Host "This prints to console output as well."
          echo "echo works as an alias for Write-Output in PowerShell"