name: Track 4 Print Metadata
run-name: This ${{github.actor}} is starting out GitHub Actions
on: [push]
jobs:
   print-job:
      runs-on: windows-latest
      steps:
      -  name: Checkout repository
         uses: actions/checkout@v4
         
      -  name: Set up JDK 21 (Eclipse Temurin)
         uses: actions/setup-java@v4
         with:
            java-version: '21'
            distribution: temurin
            cache: maven
            
      -  name: Check Java version
         run: java -version
         
      -  name: Build with Maven
         run: mvn --batch-mode clean compile package --file pascua_ex15/pom.xml
      
      -  name: Upload Build Artifact (JAR)
         uses: actions/upload-artifact@v4
         with:
            name: pascua-ex15-jar
            path: pascua_ex15/target/*.jar
     
      -  name: Print messages in PowerShell
         run: |
            Write-Output "Hello from PowerShell!"
            Write-Host "This prints to console output as well."

            echo "echo works as an alias for Write-Output in PowerShell"
     
      -  name: Print required Git and Environment Data
         run: |
            Write-Output "OS Runner Type: ${{ runner.os }}"
            Write-Output "Triggering Event: ${{ github.event_name }}"
            Write-Output "Branch Name: ${{ github.ref_name }}"
            Write-Output "Repository Name: ${{ github.repository }}"
            
      -  name: List all the files in GitHub workspace
         run: |
            Write-Output "Listing all files in workspace:"
            Get-ChildItem -Recurse | Select-Object FullName